# system
## path
server:
  port: 8088
  shutdown: graceful
  servlet:
    context-path: ${context.path}
context:
  path: /


spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 20MB # 单个文件大小
  mvc:
    throw-exception-if-no-handler-found: true


## logging level
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: WARN


grace:
  application:
    name: ${spring.application.name}
    env: ${spring.profiles.active}
