eureka:
  client:
    serviceUrl:
      defaultZone: http://9.134.197.18:9200/eureka/
    fetch-registry: true
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# 开启okhttp
feign:
  okhttp:
    enabled: true